#!/bin/bash
#Tải các file lên github
#Tài khoản tuananh1406
#pass ****88a5
#cd ssg/
url=git@github.com:tuananh1406/website.git
#git init
#git config --global user.email "huutuananh1406@gmail.com"
#git config --global user.name "Hữu Tuấn Anh"
git add --all
echo -n "Nhập mô tả thay đổi: ";read -r mota;
git commit -m "$mota"
git remote add origin $url
git remote -v
git push -f origin master

